[project]
name = "monad-exec-events"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "polars==1.32.0",
]

[build-system]
requires = ["maturin==1.8.7"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "monad_exec_events"
